### ISSUE TITLE
error when running the tool

### ISSUE THREAD

**Issue by kirincastle** [PanduKonala/Batfish-Network-Visualizer#1]
When I tried below, it throws a lot of errors, could you please advise what would be the problem? Thanks

root@ubuntu:~/Batfish-Network-Visualizer# python3 batfish_network_visualizer_v1.py
*****************************************************************************
 Batfish Network Visualizer v1.0 Created by Pandu Konala
*****************************************************************************
Traceback (most recent call last):
  File "/root/Batfish-Network-Visualizer/batfish_network_visualizer_v1.py", line 225, in <module>
    main()
  File "/root/Batfish-Network-Visualizer/batfish_network_visualizer_v1.py", line 207, in main
    initialise_batfish()
  File "/root/Batfish-Network-Visualizer/batfish_network_visualizer_v1.py", line 30, in initialise_batfish
    bf_init_snapshot(BASE_SNAPSHOT_PATH, name=BASE_SNAPSHOT_NAME, overwrite=True)
  File "/usr/local/lib/python3.10/dist-packages/pybatfish/client/commands.py", line 349, in bf_init_snapshot
    return bf_session._init_snapshot(
  File "/usr/local/lib/python3.10/dist-packages/pybatfish/client/session.py", line 957, in _init_snapshot
    return self._parse_snapshot(name, background, extra_args)
  File "/usr/local/lib/python3.10/dist-packages/pybatfish/client/session.py", line 1214, in _parse_snapshot
    answer_dict = workhelper.execute(
  File "/usr/local/lib/python3.10/dist-packages/pybatfish/client/workhelper.py", line 107, in execute
    response = resthelper.get_json_response(
  File "/usr/local/lib/python3.10/dist-packages/pybatfish/client/resthelper.py", line 78, in get_json_response
    raise BatfishException(
pybatfish.exception.BatfishException: Coordinator returned failure: {'Duplicate workId': '39f4a554-1fd6-4776-b989-46b137c1f497', 'This workId': '753bd14c-ba99-4554-8447-0b2896be04ac'}

**Comment by PanduKonala** [comment]
Hi kirincastle,

From the debug information that you have provided, I can say that the problem lies in the python package "pybatfish". Could you please try to install the below-mentioned python packages with the specific versions and get back to me:

-N2G==0.1.2

- pybatfish==2021.7.9.974

**Comment by kirincastle** [comment]
hi PanduKonala

Thanks. it is ok now. after install the specific version.

**Comment by PanduKonala** [comment]
Your welcome!
